### ISSUE TITLE
setup via requirements.txt

### ISSUE THREAD

**Issue by izipris** [tolstislon/testrail-api#23]
Hi,

Is there some known issue related to installing testrail-api via requirements.txt ?
I have a requirements.txt file, executed by` pip3 install -r requirements.txt` which includes a few packages, and in addition: `testrail_api==1.5.0`
All the packages are collected and installed, except of this one. I'm getting the following error:
```
 Could not find a version that satisfies the requirement testrail_api==1.5.0 (from -r requirements.txt (line 10)) (from versions: )
No matching distribution found for testrail_api==1.5.0 (from -r requirements.txt (line 10))
```
Already tried all the variations of testrail_api, testrail-api, 1.5, 1.5.0, etc.
Any ideas?

Thanks!

**Comment by tolstislon** [comment]
Does it work? `pip3 install testrail-api==1.5.0`

**Comment by izipris** [comment]
No :(
Getting the following error:
```
Collecting testrail-api==1.5.0
  Could not find a version that satisfies the requirement testrail-api==1.5.0 (from versions: )
No matching distribution found for testrail-api==1.5.0
```

**Comment by tolstislon** [comment]
You are using?
* Download packages from pypi
* cpython >= 3.6

I checked now. No problem

**Comment by tolstislon** [comment]
Try `pip3 install testrail-api`
If good. What version is installed?

**Comment by izipris** [comment]
Many thanks for your help.
`pip3 install testrail-api` is failed also, same error. I'm trying to install other packages such as: numpy, urllib3, unittest-xml-reporting, etc., and there is no problem with them.

**Comment by tolstislon** [comment]
I can not understand the reason

Try `pip3 install git+https://github.com/tolstislon/testrail-api.git`

**Comment by izipris** [comment]
The issue was that on my machine the Python version was 3.5.2 (thought it had 3.6). When I tried it on machine with same specifications and 3.6 it worked properly.
Thanks.

**Comment by tolstislon** [comment]
new version 1.6.0 supports python 3.5

**Comment by izipris** [comment]
you're the best, thanks!
