### ISSUE TITLE
Correct return type from Configurations API

### ISSUE THREAD

**Issue by tylervick** [tolstislon/testrail-api#26]
Hello,
I love this library! Much better than Gurock's half-baked implementation.

I noticed that the return types for configuration mutation events (add_config, add_config_group, update_config_group, etc) all have a return type of `None`.

Gurock's documentation doesn't appear to mention this, but the response body does contain the modified entity in the response. This is especially important for scenarios such as "get_or_insert".

Are you opposed to changing these types, even though it doesn't strictly match Gurock's docs? I'd be happy to open a PR for this.

**Comment by tolstislon** [comment]
Of course

**Comment by tolstislon** [comment]
@tylervick Did you refuse to open a PR?

**Comment by tylervick** [comment]
Nope, just got beyond me with everything going on :)

Opened #32 for your review, pending CI checks
