### ISSUE TITLE
is_completed in _category taking an int instead of bool, pytestrail.py takes bool instead of int

### ISSUE THREAD

**Issue by c4mmartin** [tolstislon/testrail-api#41]
I am having trouble using the get_runs(projectid=pid, is_completed=False), I believe False is a bool

I get:
testrail_api._exception.StatusCodeError: (400, 'Bad Request', 'https://testrail.link/index.php?/api/v2/get_runs/31&is_completed=False', b'{"error":"Field :is_completed is not a valid boolean."}')

_category line: 1148 get_runs
Line 1161 :key is_completed int

pytestail.py line: 339
Line 347 :type is_completed: bool
Line 356 :param is_completed: takes true/false

Sorry if i am missing something simple.

**Comment by tolstislon** [comment]
The library does not do type casting.  Use 1 - True, 0 - False

API documentation:


Name | Type | Description
-- | -- | --
:is_completed | bool | 1 to return completed test runs only. 0 to return active test runs only.

**Comment by tolstislon** [comment]
It may be worth implementing. Only there will be discrepancies with the official documentation

**Comment by tolstislon** [comment]
Implemented in version 1.7.2

**Comment by c4mmartin** [comment]
Thanks, that was quick and easy. I'll give it a test today.
