### ISSUE TITLE
Support for new bulk_api endpoints with pagination

### ISSUE THREAD

**Issue by mjones-bh** [tolstislon/testrail-api#61]
The testrail API changed on cloud for the latest release with the formal move to pagination by default: https://discuss.gurock.com/t/bulk-api-endpoint-changes-coming-soon/19537

Is there a plan to update to support this , e.g. get_cases no longer returns a list of cases but a paginated object with a 'cases' key

**Comment by tolstislon** [comment]
Thanks. In the next release

**Comment by tolstislon** [comment]
I don't understand the problem very well. Could you show with an example

**Comment by tolstislon** [comment]
It seems to me that this is beyond the scope of the wrapper api.

This can be done, but without affecting the main methods. `get_all_cases` - experimental

**Comment by dsayling** [comment]
List of confirmed bulk endpoints:

- [get_attachments_for_plan](https://support.gurock.com/hc/en-us/articles/7077196481428-Attachments#getattachmentsforplan)
- [get_attachments_for_case](https://support.gurock.com/hc/en-us/articles/7077196481428-Attachments#getattachmentsforcase)
- [get_attachments_for_run](https://support.gurock.com/hc/en-us/articles/7077196481428-Attachments#getattachmentsforrun)
- [get_cases](https://support.gurock.com/hc/en-us/articles/7077292642580-Cases#getcases)
- [get_datasets](https://support.gurock.com/hc/en-us/articles/7077300491540-Datasets#spanstylefontweight400getdatasetsspan) (not currently implemented)
- [get_groups](https://support.gurock.com/hc/en-us/articles/7077338821012-Groups#getgroups) (not currently implemented)
- [get_milestones](https://support.gurock.com/hc/en-us/articles/7077723976084-Milestones#getmilestones)
- [get_plans](https://support.gurock.com/hc/en-us/articles/7077711537684-Plans#getplans)
- [get_projects](https://support.gurock.com/hc/en-us/articles/7077792415124-Projects#getprojects)
- [get_results](https://support.gurock.com/hc/en-us/articles/7077819312404-Results)
- [get_results_for_cases](https://support.gurock.com/hc/en-us/articles/7077819312404-Results#getresultsforcase)
- [get_results_for_run](https://support.gurock.com/hc/en-us/articles/7077819312404-Results#getresultsforrun)
- [get_roles](https://support.gurock.com/hc/en-us/articles/7077853258772-Roles) (not currently implemented)
- [get_runs](https://support.gurock.com/hc/en-us/articles/7077874763156-Runs#getruns)
- [get_sections](https://support.gurock.com/hc/en-us/articles/7077918603412-Sections#getsections)
- [get_shared_steps](https://support.gurock.com/hc/en-us/articles/7077919815572-Shared-Steps#getsharedsteps)
- [get_tests](https://support.gurock.com/hc/en-us/articles/7077990441108-Tests#gettests)
- [get_variables](https://support.gurock.com/hc/en-us/articles/7077979742868-Variables) (not currently implemented)

List of possible bulk endpoints, but not explicit in documentation:
- [get_attachments_for_plan_entry](https://support.gurock.com/hc/en-us/articles/7077196481428-Attachments#getattachmentsforplanentry)
- [get_attachments_for_test](https://support.gurock.com/hc/en-us/articles/7077196481428-Attachments#getattachmentsfortest)
