### ISSUE TITLE
Issue with Plans.add_plan_entry

### ISSUE THREAD

**Issue by stevenmchaves** [tolstislon/testrail-api#91]
I use single repo style TestRail instance so suite_id is not needed.
When I use your API:
```
test_plan_response = api_client.plans.add_plan_entry(
                project_id=3,
                plan_id=None,
                suite_id=None,
                name="TEST",
                runs=runs,
)```

Here is the result:
```
File "/opt/homebrew/lib/python3.10/site-packages/testrail_api/_category.py", line 1059, in add_plan_entry
    return self.s.post(

  File "/opt/homebrew/lib/python3.10/site-packages/testrail_api/_session.py", line 171, in post
    return self.request(

  File "/opt/homebrew/lib/python3.10/site-packages/testrail_api/_session.py", line 215, in request
    return response if raw else self.__response_handler(response)

  File "/Users/steven/pytest-reporting/pytest_testrail/pytest_testrail/api.py", line 54, in response_handler
    raise requests.HTTPError(f"Unexpected status code.  {details}")

requests.exceptions.HTTPError: Unexpected status code.          STATUS CODE RECEIVED: 400 - EXPECTED STATUSES: [200, 201]
        REQUEST: <PreparedRequest [POST]> URL: '/index.php?/api/v2/add_plan_entry/None'
```

I shouldn't need to supply either plan_id or suite_id. Notice the None 
`'/index.php?/api/v2/add_plan_entry/None'`
The None should be project_id should be `3` since the TestRail API wants the project-id

**Comment by dsayling** [comment]
This is not an incorrect method call
```python
test_plan_response = api_client.plans.add_plan_entry(
                project_id=3,
                plan_id=None,
                suite_id=None,
                name="TEST",
                runs=runs,
)
```

Given the documentation [here](https://github.com/tolstislon/testrail-api/blob/master/testrail_api/_category.py#L1028), the method call should be as such:

```
response

**Comment by stevenmchaves** [comment]
Misread the API. Closing
